services:
  account-postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=bill_clinton
      - POSTGRES_PASSWORD=2001
      - POSTGRES_DB=account_service
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - account-postgres-data:/var/lib/postgresql/data
    networks:
      - account-network

  account-postgres-test:
    image: postgres:latest
    environment:
      - POSTGRES_USER=mazafaker322
      - POSTGRES_PASSWORD=CEUvt7$12g
      - POSTGRES_DB=account_service_test
    ports:
      - "5434:5432"
    restart: unless-stopped
    volumes:
      - account-postgres-test-data:/var/lib/postgresql/data
    networks:
      - account-network

  transaction-postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=solid_snake
      - POSTGRES_PASSWORD=gv%R*uJBHI)J
      - POSTGRES_DB=transaction_service
    ports:
      - "5433:5432"
    restart: unless-stopped
    volumes:
      - transaction-postgres-data:/var/lib/postgresql/data
    networks:
      - transaction-network

  transaction-postgres-test:
    image: postgres:latest
    environment:
      - POSTGRES_USER=kokojambo
      - POSTGRES_PASSWORD=V(&IYBo97t6f
      - POSTGRES_DB=transaction_service_test
    ports:
      - "5435:5432"
    restart: unless-stopped
    volumes:
      - transaction-postgres-test-data:/var/lib/postgresql/data
    networks:
      - transaction-network

#  redis:
#    image: redis:latest
#    ports:
#      - "6379:6379"
#    restart: unless-stopped
#    command: redis-server --requirepass ${REDIS_PASSWORD}
#    environment:
#      - REDIS_PASSWORD=${REDIS_PASSWORD}
#    volumes:
#      - redis-data:/var/lib/redis/data

volumes:
  account-postgres-data:
  account-postgres-test-data:
  transaction-postgres-data:
  transaction-postgres-test-data:
#  redis-data:

networks:
  account-network:
    driver: bridge
  transaction-network:
    driver: bridge
