services:
  account-postgres:
    container_name: account-postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=bill_clinton
      - POSTGRES_PASSWORD=2001
      - POSTGRES_DB=account_service
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - account-postgres-data:/var/lib/postgresql/data
    networks:
      - payment-system-network

  account-postgres-test:
    container_name: account-postgres-test
    image: postgres:latest
    environment:
      - POSTGRES_USER=mazafaker322
      - POSTGRES_PASSWORD=CEUvt7$12g
      - POSTGRES_DB=account_service_test
    ports:
      - "5434:5432"
    restart: unless-stopped
    volumes:
      - account-postgres-test-data:/var/lib/postgresql/data
    networks:
      - payment-system-network

  transaction-postgres:
    container_name: transaction-postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=solid_snake
      - POSTGRES_PASSWORD=gv%R*uJBHI)J
      - POSTGRES_DB=transaction_service
    ports:
      - "5433:5432"
    restart: unless-stopped
    volumes:
      - transaction-postgres-data:/var/lib/postgresql/data
    networks:
      - payment-system-network

  transaction-postgres-test:
    container_name: transaction-postgres-test
    image: postgres:latest
    environment:
      - POSTGRES_USER=kokojambo
      - POSTGRES_PASSWORD=V(&IYBo97t6f
      - POSTGRES_DB=transaction_service_test
    ports:
      - "5435:5432"
    restart: unless-stopped
    volumes:
      - transaction-postgres-test-data:/var/lib/postgresql/data
    networks:
      - payment-system-network

  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:7.4.0
    ports:
      - "9092:9092"
      - "9101:9101"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:29093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      CLUSTER_ID: MkU3OEVBNkYwNkJCMzJBQg==
    volumes:
      - kafka-data:/var/lib/kafka/data
    networks:
      - payment-system-network

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    depends_on:
      - kafka
    ports:
      - "8081:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    networks:
      - payment-system-network

volumes:
  account-postgres-data:
  account-postgres-test-data:
  transaction-postgres-data:
  transaction-postgres-test-data:
  kafka-data:

networks:
  payment-system-network:
    driver: bridge
