server:
  host: ""
  port: 50052

postgres:
  host: localhost
  port: 5433
  database: transaction_service
  sslmode: disable
  max_conns: 10
  min_conns: 2
  max_conn_lifetime: 1h
  max_conn_idle_time: 30m

kafka:
  brokers: [ "localhost:29092" ]
  group_id: "transaction-service"
  topics:
    results: "transactions.results"
    created: "transactions.created"