syntax = "proto3";

package account.v1;

option go_package = "github.com/mibrgmv/payment-system/services/gateway/internal/protogen/account/v1;accountv1";

import "google/protobuf/timestamp.proto";
import "google/protobuf/empty.proto";
import "google/protobuf/field_mask.proto";
import "google/api/annotations.proto";

service AccountService {
  rpc GetAccount(GetAccountRequest) returns (Account) {
    option (google.api.http) = {
      get: "/api/v1/accounts/{account_id}"
    };
  }

  rpc ListAccounts(ListAccountsRequest) returns (ListAccountsResponse) {
    option (google.api.http) = {
      get: "/api/v1/accounts"
    };
  }

  rpc CreateAccount(CreateAccountRequest) returns (Account) {
    option (google.api.http) = {
      post: "/api/v1/accounts"
      body: "*"
    };
  }

  rpc UpdateAccount(UpdateAccountRequest) returns (Account) {
    option (google.api.http) = {
      patch: "/api/v1/accounts/{account.account_id}"
      body: "account"
    };
  }

  rpc DeleteAccount(DeleteAccountRequest) returns (google.protobuf.Empty) {
    option (google.api.http) = {
      delete: "/api/v1/accounts/{account_id}"
    };
  }

  rpc GetBalance(GetBalanceRequest) returns (Balance) {
    option (google.api.http) = {
      get: "/api/v1/accounts/{account_id}/balance"
    };
  }
}

message Account {
  string account_id = 1;
  string user_id = 2;
  Currency currency = 3;
  google.protobuf.Timestamp created_at = 4;
  google.protobuf.Timestamp updated_at = 5;
}

message Balance {
  string account_id = 1;
  double amount = 2;
  Currency currency = 3;
  google.protobuf.Timestamp last_updated = 4;
}

message GetAccountRequest {
  string account_id = 1;
}

message ListAccountsRequest {
  string user_id = 1;
  int32 page_size = 2;
  string page_token = 3;
}

message ListAccountsResponse {
  repeated Account accounts = 1;
  string next_page_token = 2;
}

message CreateAccountRequest {
  string user_id = 1;
  Currency currency = 2;
}

message UpdateAccountRequest {
  Account account = 1;
  google.protobuf.FieldMask update_mask = 2;
}

message DeleteAccountRequest {
  string account_id = 1;
}

message GetBalanceRequest {
  string account_id = 1;
}

enum Currency {
  CURRENCY_UNSPECIFIED = 0;
  CURRENCY_RUB = 1;
  CURRENCY_USD = 2;
  CURRENCY_EUR = 3;
}